# Site settings
title: Chris Hull | Staff Software Engineer
email: c.hullcse@protonmail.com
description: >-
  Chris Hull is a Staff Software Engineer focused on distributed systems,
  edge and embedded AI, cloud infrastructure, and machine learning platforms.
baseurl: ""
url: "https://loadinginprogress.com"

twitter_username:
github_username:

# Build settings
markdown: kramdown
